version: '1.0'
services:
    db:
        container_name: mysql
        image: mysql:8.0.31
        # build:
        #     context: .
        #     dockerfile: db.Dockerfile
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: devbook
        command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
        restart: always
    api:
        container_name: api
        depends_on:
            - db
        build:
            context: .
            dockerfile: api.Dockerfile
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - .:/app/
networks:
    default:
volumes:
    mysql_data:
